### ISSUE TITLE
Gui - Experience

### ISSUE THREAD

**Issue by disconsented** [disconsented/ANSSRPG#33]

**Comment by Jon11888** [comment]
Is experience for ANSSRPG separate from the experience orbs and experience bar for vanilla minecraft? I can see about making some kind of graphical representation for an experience bar, and then tweak and edit it to fit with what is needed.

**Comment by disconsented** [comment]
Yes it is separate, experience is unique to each skill. Design here really isn't my thing but in a net shell I would like a GUI that can neatly show: The name of the skill, then a graphical and/or numerical representation of the exp. Maybe something like http://i.imgur.com/cgiRRGo.png but contained within a book so then I can use additional pages to handle overflow?

**Comment by Jon11888** [comment]
Ok, that gives me some specifics to work from, I should be able to make something tomorrow or the next day.

**Comment by disconsented** [comment]
Cheers I look forward to see what you drum up

**Comment by disconsented** [comment]
Anything to share @Jon11888 ?

**Comment by Jon11888** [comment]
Hey, I'm sorry, my work schedule has been completely insane these last few weeks, I was hoping to have more work done by now. I'll let you know as soon as I have something ready. Again, really sorry about that.

**Comment by disconsented** [comment]
No worries your personal life comes first

**Comment by Jon11888** [comment]
Ok, here's a rough draft, something along the lines of what I had in mind. http://imgur.com/JGTCx5Z Will you be able to work with this, or should I make 100 frames so that there is an image for each percentage? If there is any aspect you want changed, let me know.

**Comment by disconsented** [comment]
I should be able to make it work with some programming magic, looking great by the way

**Comment by dmodoomsirius** [comment]
Looks good tho users might want to know what percentage they are at. so thats something to keep in mind. they might not be able to tell what the bar is showing.

**Comment by Jon11888** [comment]
Well, the fancy green swirly lines are optional, I can make a version with a solid bar, I just like to include fractal art whenever possible.

**Comment by disconsented** [comment]
A solid bar is preferred as it requires less work for me :)

**Comment by Jon11888** [comment]
Here is the second version, if there's anything else that you'd like changed let me know. http://i.imgur.com/udJSKk4.png

**Comment by disconsented** [comment]
Looks great! Now time to chop it up and implement it

**Comment by Jon11888** [comment]
Oh, duh, I forgot all about that. I'm thinking of also adding a field for the exact exp level, in addition to the percentage. Give me a few minutes, Should have it up within 15 to 20.

**Comment by disconsented** [comment]
Awesome, if you want you can include a makers mark as a separate image or put your name in the credits

**Comment by Jon11888** [comment]
Hmm, well I'll wait till you see the next version, then I'll include my name in the image on the final version.

**Comment by Jon11888** [comment]
http://i.imgur.com/Lg1LVVY.png

**Comment by disconsented** [comment]
I think I will go with the second from the bottom style but include the #-># from below it

**Comment by Jon11888** [comment]
http://i.imgur.com/3lxEEqA.png
Ok, I think this should work as needed.

**Comment by Jon11888** [comment]
Also, Not sure if this is the right area to discuss this, but will you be needing a server to test this project on? Just thought I'd ask, I may come into possession of a server sometime in the next few days, just thought I'd mention it in case you have need of a minecraft server.

**Comment by disconsented** [comment]
I test this on my personal machine so I am fine in that regard, feel free to use it if you want however :)

**Comment by Jon11888** [comment]
Sounds good.

**Comment by disconsented** [comment]
http://puu.sh/hFoiB/0fa9344f0b.jpg All rendered in game :)
Could you tweak some of the boxes that currently are a bit too small? (length wise)

**Comment by disconsented** [comment]
This is basically done for now so I will close the issue
