### ISSUE TITLE
Attributes

### ISSUE THREAD

**Issue by Jon11888** [disconsented/ANSSRPG#37]
Attributes could govern general player stats while also working as categories that each skill could fit under. 

I would think that a few stock ideas could be as follows: 
Vitality
-increases max health
-armor or defensive skills could fall under Fortitude
Strength
-Increases max item stacks past 64 blocks when higher than average. 
-Melee type skills could fall under strength
Endurance
-decreases the speed at which the hunger bar decreases by running or healing
-tool using skills could fall under endurance
Dexterity
-chance to dodge attacks
-crafting and movement based skills could fall under Dexterity

There are a few options I've thought of for how attributes can be increased separately from skills:
-Each time a player reaches a total skill level milestone they could pick an attribute to increase.
-When the skills under an attribute increase, so does the attribute.
-Selecting a class could consist of picking a favored attribute that is increased at the start

**Comment by disconsented** [comment]
Thinking about it now this may work well as a perk sub-type

**Comment by skittishtrigger** [comment]
Good idea with proper implementation. As long as stts stay somewhat modifier with neg attributes at start (chance at failure at something?) and like a max of +10 to abilities at most at max.
