### ISSUE TITLE
Discussion: Make required on client

### ISSUE THREAD

**Issue by disconsented** [disconsented/ANSSRPG#38]
I have been thinking about about the actions perks and I have yet to figure out a reliable way to allow a player to use them without a clientside component. I can do commands but those are just ugly to use.

Thoughts?

**Comment by TehNut** [comment]
I honestly don't see a reason why not. Opens it up to many more options.

If you need to, just add a config for anything that would require the client to be installed so that servers can continue to use it without requiring extra downloads on the player's end.

**Comment by Jon11888** [comment]
I kindof like the idea of using commands for Magic like skills, where the time to type them acts as a casting time of sorts, I suppose it could also work for other things as well. Here's another idea, what if you set an "Active" ability using a command, and pressing a particular button uses it in game without using a command, after using the initial command to set your active ability. That would limit you to one at a time, unless we have more than one action command. Hmm, I've been playing too much Transistor, perhaps, but what about being able to use a command to set an ability to each of the number keys? so, you would type somthing like "/Skill Ability Number" and it will set it to the corresponding key. "/Axes Cripple 3" would mean that the cripple ability, under the axes skill would activate when pressing 3. Is that feasible to code? Just listing the first few ideas that came to mind.

**Comment by disconsented** [comment]
Decided to go with TehNut's idea
