### ISSUE TITLE
Skills without fail states

### ISSUE THREAD

**Issue by disconsented** [disconsented/ANSSRPG#39]
In response to #8 I have been thinking about implementing the Smelting Skill (as well as fishing) without failure states. Thoughts?

**Comment by skittishtrigger** [comment]
Not a bad idea, the smelting skill could provide a bonus to to amount of ore able to be obtained with smelting. Same as bonus loot with fishing. maybe add farming skill? like decrease in tool damage when using hoe and an increases in loot harvested?
