### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by skittishtrigger** [disconsented/ANSSRPG#42]
basic permissions to use the /anssrpg 0/1 default to denied.  listing of perms or defaulting to allow needed.

**Comment by disconsented** [comment]
As of DEV22 (https://github.com/disconsented/ANSSRPG/commit/1b4a36c573ac0ced2b152567ab0ceca7c2231d36) commands are set to always allow. Any issue will be with how software like Cauldron handles overriding permissions (apparently list of permissions are given within server logs on startup)

**Comment by disconsented** [comment]
should be looking for somthing like ```disconsented.anssrpg.commands.ANSSRPG```

**Comment by TehNut** [comment]
Just told @disconsented about this on IRC, but dropping it here for publicity's sake:

All that needs to be done is add this to [ANSSRPG.java](https://github.com/disconsented/ANSSRPG/blob/DEV/src/main/java/disconsented/anssrpg/commands/ANSSRPG.java)

```java
    @Override
    public int getRequiredPermissionLevel() {
        return 0;
    }
```
