### ISSUE TITLE
BC interference

### ISSUE THREAD

**Issue by skittishtrigger** [disconsented/ANSSRPG#45]
Mod progression interferes with Current version of BC(7.0.13 atm) Quarry hits any vanilla ore it halts all but obsidian.

**Comment by disconsented** [comment]
For now I will implement white/black list (config option) for all fake players
Post RC1 I hope to "tag" blocks as they're placed and from there do the relevant checks

**Comment by disconsented** [comment]
Forgot to mention this but as of v0.2.# I have a basic implementation that will either block or allow fake players based on an config option
