### ISSUE TITLE
Wiki and Updates

### ISSUE THREAD

**Issue by oInward** [disconsented/ANSSRPG#54]
Wanted to know how updated the Wiki is as It seems to help me much with the mod.
Would it be possible to add some examples of some configs for some pre made ones?
Just to better understand how and what to change?

**Comment by disconsented** [comment]
Thanks for reminding me. The wiki has been replace with [guide.rst](https://github.com/disconsented/ANSSRPG/blob/DEV/guide.rst) however I am in the process of porting to 1.8 at the moment which has forced me to change how block perks and skills work (have to replace metadata with properties)

**Comment by oInward** [comment]
Okay this helps immensely! So will there still be updates for the 1.7.10 versions or will you just focus on the 1.8 versions?

**Comment by disconsented** [comment]
1.8 is intended to be the primary focus unless something nasty crops up

**Comment by disconsented** [comment]
I am active on [IRC for the next few hours if you wish to chat](https://kiwiirc.com/client/irc.esper.net/?#disconsented) (or #disconsented on irc.esper.net)
