### ISSUE TITLE
new Permanent skills and Toggeable & a spotlight request

### ISSUE THREAD

**Issue by Carbon-Ghost** [disconsented/ANSSRPG#56]
I would love to have some permanent skills that keep with you when you die and can't be removeable, I am thinking of slowfall ( no fall damage and gliding ), regenerator, Divine shield ( 10% damage absorption ), swiftness ( faster movement speed ). 

And some toggeable skills, basically allows you to cast projectiles by using a Magic Points pool ( default 1000 and +1 per second regen ) some default projectiles will exist but more will be able to be added with configs, press 0 to use magic, it will display your hand with a small electric ball :D 

The following projectile styles are here : 
-Basic projectile ( just fly forward ) 
-Gravity affected projectile ( like arrows )
-Bouncing projectile
-Piercing projectile ( go through multiple mobs for crowd control )

Modifiers are : 
-Homing
-Fast fire ( auto fire, can be set up to 20 projectiles per second )
-Fire imbued
-Slowness imbued
-Darkness/Blindness imbued
-Poison imbued
-Knockback

note some can't go together due to practical reasons ( piercing + homing is the only one atm )

Last thing, I would love to have someone doing a spotlight, although documentation is here, it's too complex for me :/ And I am having a hard time :C 

I would also appreciate to have a continuation of 1.7.10

**Comment by TehNut** [comment]
>I would also appreciate to have a continuation of 1.7.10

Yup that's my job.

**Comment by Carbon-Ghost** [comment]
lol

**Comment by disconsented** [comment]
Permanent perks should be pretty easy to get working (Just need to adjust some logic).
Toggles are something I want to do (Should be pretty easy to add).
As long as it is a potion effect it can be added in as a new perk.

[As for additional resources.. Ill think about it](https://docs.google.com/document/d/1hfSOAJAT4HWMPomyKIv9-gUXS4q0sN0s02wGQbNQuH0/edit?usp=sharing)

Would be cool if someone did a spotlight but I am not particularly keen on seeking out someone to do it

**Comment by Carbon-Ghost** [comment]
please don't yell at me, I still have some difficulties to understand this mod due to the level of awesomeness..

**Comment by disconsented** [comment]
I wasn't yelling :<

**Comment by TehNut** [comment]
YES YOU WERE.

**Comment by disconsented** [comment]
Rude :^)

**Comment by Carbon-Ghost** [comment]
xD

**Comment by disconsented** [comment]
But you should yell at @TehNut to get 1.7.10 out ;)

**Comment by Carbon-Ghost** [comment]
xD Nah, I won't, I'm too nice ;P 
But you get the idea, moar skills, moar json, moar configurability, moar flexibility :3

**Comment by disconsented** [comment]
I have lots of things I want to do, just need to find the time to do them ;) (Hint: Contributing to docs and stuff makes my life easier).

No real point keeping this open, if you want to chat then you can follow the info in readme.md for our IRC info :)

**Comment by Carbon-Ghost** [comment]
Roger that ^-^
