### ISSUE TITLE
1.8 version not compatible with 1.8.9

### ISSUE THREAD

**Issue by katubug** [disconsented/ANSSRPG#62]
Getting an error that says that this mod wants a different version of minecraft (1.8.1 something), and won't run.

**Comment by disconsented** [comment]
Ill get a new version out when I have some free time later

**Comment by katubug** [comment]
Awesome, thanks!

**Comment by disconsented** [comment]
I've done too much between 1.8 and 19.+ for it to be feasible for me to backport or update. Sorry :(

**Comment by katubug** [comment]
That's cool, no worries! Thanks for looking into it!
