### ISSUE TITLE
[Suggestion] Mod Support

### ISSUE THREAD

**Issue by GazbonicAcid** [disconsented/ANSSRPG#63]
How is the mod support?
What I mean is can ANSSRPG support the following for skills/perks?
Right click specified mod blocks with specified mod item?
Automatically setting/changing specified nbt tags in said mod item?
Crafting of specifed mod items adding xp to specified skills?
Require varying levels of specified set of skills for specified perk?

Even though the Progression was updated a little more recently, I would prefer to use ANSSRPG for tech progression as both I believe it would be easier to do what I want.
At the very least, it would be easier to set certain stuff to unlock based on a leveling system.
As for the mod support I asked about,
I am thinking of making an "Engineering" skill.
With certain crafting and certain multi-blocks being unlocked according to skill levels.
I need auto nbt tag setting/changing because Immersive Engineering supports using nbt tags on its Engineer's Hammer to blacklist and whitelist what multiblocks that that hammer is allowed to form.
Also, would it be possible to add support for server permissions systems?
For example, player only getting permission X if they have a certain skill level?
Generic all-round permission set would be nice, but I'd also like support for the rules system of Sponge plugin "[Permissions Manager](https://minecraft.curseforge.com/linkout?remoteUrl=https%253a%252f%252fforums.spongepowered.org%252ft%252fkey-permissionmanager-v2-5-2-api-6-x-5-x-4-2-0-gb-fr-ru-and-more%252f12310)"

As for the multiblock formation whitelist/blacklist,
I don't know how it works in the code.
All I do know is that pack-authors/server-owners like me can do so by adding an nbt tag to the engineer's hammer.

**Comment by disconsented** [comment]
So I have a prototype which will work fine for perks (if a perk is present for X then its required before the action can pass) however support skill side for this is still up in the air.

**Comment by disconsented** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/1502#issuecomment-250000755 for reference later

**Comment by disconsented** [comment]
Lets keep this open for now
