### ISSUE TITLE
[Skill] Cooking

### ISSUE THREAD

**Issue by Dark-Arcana** [disconsented/ANSSRPG#8]
Reference #7

**Comment by disconsented** [comment]
Decided to reopen this for input.
Essentially there is no direct way  to do this. However @Serializer proposed a system involving tagging items (list of UUID's) as they are placed into the furnace and then applying XP when removed. However tracking is iffy at best. More research needed

**Comment by TBotV63** [comment]
Tag the furnace as items are placed into it?

**Comment by disconsented** [comment]
At this point I have scrapped it from the first RC. At this point this will require more effort than I am willing to put in, heavy ASM will be required if it is possible with the current code base

**Comment by disconsented** [comment]
No point having this open at the moment
